[build]
  command = "npm install && npm run build"
  functions = "functions"

[functions]
  included_files = ["assets/*","sitemap/*","*"]

[[redirects]]
  from = "/*"
  to = "/.github/functions/core/:splat"
  status = 200
  force = true
